# --- PostgreSQL profile ---

spring.datasource.url=jdbc:postgresql://postgres:5432/taskflow
spring.datasource.username=taskflow
spring.datasource.password=taskflow
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ??????????????? false ??OK
spring.jpa.show-sql=false

# H2 console ?Postgres????
spring.h2.console.enabled=false


