create table tasks (
  id bigint generated by default as identity primary key,
  title varchar(100) not null,
  description varchar(1000),
  status varchar(20) not null,
  priority varchar(20) not null,
  due_date date
);

create index idx_tasks_status on tasks(status);
create index idx_tasks_priority on tasks(priority);
create index idx_tasks_due_date on tasks(due_date);
